apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpfrontend
  labels:
    app: mpfrontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mpfrontend
  template:
    metadata:
      labels:
        app: mpfrontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: mpfrontend
        image: aouyang1/mpfrontend:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
