apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-rewrite-ingress
spec:
  rules:
  - host: grafana.austin-ouyang.com
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 80
